name: reactive_date_time_picker
description: Wrapper around showDatePicker and showTimePicker to work with reactive_forms
version: 4.5.0
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_date_time_picker
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.18.0 <1.0.0"
  reactive_forms: ">=16.0.0 <18.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
