name: reactive_checkbox_list_tile
description: Wrapper around CheckboxListTile to use with reactive_forms.
version: 0.0.1
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_checkbox_list_tile
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ">=16.0.0 <18.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2