name: reactive_input_decorator
description: Wrapper around input_decorator to use with reactive_forms.
version: 0.0.8
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_input_decorator
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ">=16.0.0 <18.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0