name: reactive_phone_form_field
description: Wrapper around phone_form_field to use with reactive_forms
version: 5.0.1
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_phone_form_field
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ">=16.0.0 <18.0.0"
  phone_form_field: ^10.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0